#!/usr/bin/env python
# -*- coding: utf-8 -*-

import tensorflow as tf

if __name__ == '__main__':
    model = tf.keras.models.load_model('../models/genre_model')
    model.summary()
    #load
    #predict
    #pre
    
