#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import tensorflow as tf
from audiosep.train import Trainer

JSON_PATH = "C:/Users/cezea/code/ChikeMartin/audiosep/raw_data/genre/data.json"
#model_path = "C:/Users/cezea/code/ChikeMartin/audiosep/models/"
#model = "genre_model.h5"

if __name__ == '__main__':
    #model = tf.keras.models.load_model(model_path + model)
    #model.predict_new_song(file)
    file = sys.argv[1]
    train = Trainer(JSON_PATH)
    train.train(epochs= 30, verbose= 2)
    print('\n')
    train.evaluate(test= True)
    print('\n')
    train.predict_new_song(file)
